Release new version to market
axonivy-market/azure-blob-connector pull request #3
Opened 2024-08-12 05:25 UTC by trungmaihova

2024-08-12 10:07 UTC, ntqdinh-axonivy requested changes
A pretty cool connector. I also raise some feedback before we release. Could you check it and discuss with me if needed?

2024-08-14 01:31 UTC, trungmaihova commented on azure-blob-connector-demo/README.md
> +	ACCOUNT_KEY: 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='
Done

2024-08-14 01:32 UTC, trungmaihova commented on azure-blob-connector-demo/src/com/axonivy/cloud/storage/bean/UploadBean.java
> +	private void getBlobs(List<BlobItem> bis) {
Done

2024-08-14 01:44 UTC, trungmaihova commented on azure-blob-connector-demo/src/com/axonivy/cloud/storage/bean/UploadBean.java
> +							new FacesMessage(FacesMessage.SEVERITY_INFO, "Uploaded blobs successfully", null));
Done

2024-08-14 01:45 UTC, trungmaihova commented on azure-blob-connector-demo/src/com/axonivy/cloud/storage/bean/UploadByCallSubprocess.java
> +	public void getBlobs(List<BlobItem> bis) {
Done

2024-08-14 01:48 UTC, trungmaihova commented on azure-blob-connector-demo/src/com/axonivy/cloud/storage/utils/UploadUtils.java
> +		} catch (URISyntaxException e) {
It should be URISyntaxException  because it is a url link
![image](https://github.com/user-attachments/assets/424571f7-1735-4350-8fc8-754734fcb1d2)

2024-08-14 03:02 UTC, trungmaihova commented on azure-blob-connector-demo/src_hd/com/axonivy/cloud/storage/demo/Upload/Upload.xhtml
> +					<p:dataTable id="blobTable" style="with:100%"
Done

2024-08-14 03:06 UTC, trungmaihova commented on azure-blob-connector-demo/src_hd/com/axonivy/cloud/storage/demo/Upload/resources/uploadDialog.css
> +.width-100-percent {
Done

2024-08-14 03:07 UTC, trungmaihova commented on azure-blob-connector-demo/src_hd/com/axonivy/cloud/storage/demo/Upload/Upload.xhtml
> +				<p:fieldset id="uploadByURL" style="margin-top:10px;"
Done

2024-08-14 03:08 UTC, trungmaihova commented on azure-blob-connector-demo/src_hd/com/axonivy/cloud/storage/demo/Upload/Upload.xhtml
> +				</p:fieldset>
It just a demo. so we should keep this now. It should improve in next version

2024-08-14 03:13 UTC, trungmaihova commented on azure-blob-connector/src/com/axonivy/cloud/storage/azure/blob/connector/internal/AzureBlobStorageService.java
> +		BlockBlobClient blockBlobClient = getBlobClient(blobName).getBlockBlobClient();
It is always not null because it just create a client to access azure blob.

2024-08-14 03:50 UTC, ntqdinh-axonivy requested changes
there was an typo mistake it refactored code. Could you please check it?

2024-08-14 03:50 UTC, ntqdinh-axonivy commented on azure-blob-connector-demo/src/com/axonivy/cloud/storage/bean/UploadBean.java
> +	private void fetchAllBlobsAndAdMessage(String message) {
fetchAllBlobsAndAdMessage typo mistake => fetchAllBlobsAndAddMessage

2024-08-14 08:13 UTC, ntqdinh-axonivy approved these changes
LGTM

2024-08-14 08:16 UTC, merged